name: EnchantNow
version: '${version}'
main: com.lojosho.enchantnow.EnchantNow
api-version: 1.16
authors: [ LoJoSho ]
description: A Minecraft plugin that allows better enchanting with commands
softdepend:
  - EcoEnchants
commands:
  enchantbook:
    description: "Basic enchantment command"
  enchant:
    description: "An enchant command"
  enchantreload:
    description: "Reloads the plugin"
permissions:
  enchantnow.reload:
    default: false
  enchantnow.givebook:
    default: false
  enchantnow.enchant:
    default: false